### ISSUE TITLE
Possible merge or refractoring

### ISSUE THREAD

**Issue by IoakeimSogiakas** [CSpyridakis/lcd-greek-chars#2]
Μιας και η βιβλιοθήκη αφορά ελληνικά γράμματα, θα μιλήσω στα ελληνικά.

Επειδή φτιάχνω ένα project με Liquid Crystal, χρειάστηκα μια βιβλιοθήκη για ελληνικούς χαρακτήρες. Παράδοξα, δεν έψαξα καθόλου στο Google και απλά την έφτιαξα μόνος μου. Είναι πολύ παρόμοια με τη δική σου. Αρχικά, χρησιμοποίησα και εγώ τον ίδιο χαρακτήρα από τη ROM της οθόνης, αλλά βρήκα μια καλύτερη λύση. Υπάρχει ένας χαρακτήρας που μοιάζει πολύ με το γράμμα Θ, και έτσι μπορείς να έχεις κανονικά το γράμμα Ω.

Επιπλέον έχω κάνει αρκετά overloading στην πλευρά της βιβλιοθήκης ώστε να δουλεύει καλά (για εμένα)

**Comment by CSpyridakis** [comment]
Καλησπέρα, είδα την λύση και φαίνεται όντως χρήσιμη. Δεν ξέρω γιατί δεν το είχα παρατηρήσει όταν φτιάχτηκε ¯\_(ツ)_/¯ Ευχαριστώ για το issue :) θα το προσθέσω να υπάρχει στο header.
